In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv("gdrive/My Drive/Datasets/Iris.csv",index_col = 'Id')
data

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id                                                                           
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
data['Species'].replace({'Iris-setosa':1,'Iris-virginica':-1,'Iris-versicolor':-1},inplace=True)
data

<ipython-input-4-fe156b383271>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Species'].replace({'Iris-setosa':1,'Iris-virginica':-1,'Iris-versicolor':-1},inplace=True)
<ipython-input-4-fe156b383271>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Species'].replace({'Iris-setosa':1,'I

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
Id                                                                    
1              5.1           3.5            1.4           0.2        1
2              4.9           3.0            1.4           0.2        1
3              4.7           3.2            1.3           0.2        1
4              4.6           3.1            1.5           0.2        1
5              5.0           3.6            1.4           0.2        1
..             ...           ...            ...           ...      ...
146            6.7           3.0            5.2           2.3       -1
147            6.3           2.5            5.0           1.9       -1
148            6.5           3.0            5.2           2.0       -1
149            6.2           3.4            5.4           2.3       -1
150            5.9           3.0            5.1           1.8       -1

[150 rows x 5 columns]

In [5]:
X = np.array(data.iloc[:,:-1])
Y = np.array(data.iloc[:,-1])

In [6]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
Y

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [46]:
import numpy as np

class SVM:
    """
    Support Vector Machine (SVM) classifier implemented using batch gradient descent.
    """

    def __init__(self, epochs=500, learning_rate=0.01, C=1.0,lambda_=0.01):
        print("SVM initialized")
        self.epochs = epochs
        self.learning_rate = learning_rate
        self.C = C
        self.w = None
        self.b = None
        self.lambda_ = lambda_

    def initial_weights(self, features):
        print("Initializing weights")
        weights = np.zeros(features)  # Start with zeros for stability
        bias = 0
        return weights, bias

    def hypothesis(self, X):
        return np.dot(X, self.w) + self.b

    def hinge_loss(self, y_pred, Y):
        return np.sum(np.maximum(0, 1 - Y * y_pred))

    def train(self, X, Y):
        print("Training started")
        num_features = X.shape[1]
        self.w, self.b = self.initial_weights(num_features)

        for i in range(self.epochs):
            y_pred = self.hypothesis(X)
            margin = Y * y_pred

            # Compute gradients
            gradient_w = np.zeros_like(self.w)
            gradient_b = 0

            for j in range(len(X)):
                if margin[j] < 1:
                    gradient_w += (-self.C * Y[j] * X[j]) + (2 * self.lambda_ * self.w)  # L2 penalty
                    gradient_b += (-self.C * Y[j])  # No L2 penalty on bias


                # gradient_w += self.w  # Regularization term

            # Average gradients
            gradient_w /= len(X)
            gradient_b /= len(X)

            # Update weights and bias
            self.w -= self.learning_rate * gradient_w
            self.b -= self.learning_rate * gradient_b

            if i % 100 == 0:
                loss = self.hinge_loss(y_pred, Y)
                print(f"Epoch {i}, Loss: {loss}")

        print("Training completed")

    def predict(self, X):
        y_pred = self.hypothesis(X)
        return np.sign(y_pred)


In [49]:
s = SVM(epochs=1000,learning_rate=0.1,C=1.0,lambda_=0.01)
s.train(X,Y)
print(s.w)
print(s.b)

SVM initialized
Training started
Initializing weights
Epoch 0, Loss: 150.0
Epoch 100, Loss: 0.31738879641246553
Epoch 200, Loss: 0.14392673319203309
Epoch 300, Loss: 0.024716265024351203
Epoch 400, Loss: 0.0
Epoch 500, Loss: 0.0
Epoch 600, Loss: 0.0
Epoch 700, Loss: 0.0
Epoch 800, Loss: 0.0
Epoch 900, Loss: 0.0
Training completed
[ 0.23195337  0.60329456 -1.08480385 -0.52931648]
0.1440000000000001


In [ ]:
x = np.array([[1,2,3],
              [2,3,4],
              [1,2,3]])
y = np.array([1,2,3])
z = np.dot(x,y)
z

array([14, 20, 14])

Weights: [[ 0.1834247   0.45491749 -0.81478125 -0.43387895]]
Bias: [0.10849737]


Hinge Loss: 0.00450754082806682
